### ISSUE TITLE
Support `console.log()` for cloudstate transaction objects

### ISSUE THREAD

**Issue by kevgug** [freestyle-sh/cloudstate#17]
No support for `console.log()` directly on `getRoot("xxxxxxx")` makes debugging test cases more difficult.

### Any test file 
```js
{
  const object = {
    value: "hello" // can be any value
  };

  setRoot("test-root", object);
  commit();
}

{
  const root = getRoot("test-root");
  console.log("root", root);
}
```

### Terminal output
```
root [Internal Formatting Error] TypeError: Cannot convert a Symbol value to a string
    at parseInt (<anonymous>)
    at Object.get (ext:cloudstate/cloudstate.js:499:23)
    at formatRaw (ext:deno_console/01_console.js:621:18)
    at formatValue (ext:deno_console/01_console.js:529:10)
    at formatProperty (ext:deno_console/01_console.js:1618:11)
    at formatRaw (ext:deno_console/01_console.js:931:9)
    at formatValue (ext:deno_console/01_console.js:529:10)
    at inspectArgs (ext:deno_console/01_console.js:3043:17)
    at console.log (ext:deno_console/01_console.js:3112:7)
    at file:///xxxxxxxx/cloudstate/runtime/tests/xxxxxxxx:15:11
```

**Comment by harshsbhat** [comment]
Sounds fair. Would love to tackle this. But we'll need some time to understand the codebase if you don't mind.
